spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/umanager
        username: root
        password: 1234
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

main.classpath: G:\MyReponsitory\demo\src\main\resources

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.boot.test.demo.mapper
logging:
  level: debug
server:
  port: 9999
